name: 'Build and Deploy to GitHub Pages'
description: 'Build and deploy the static site to GitHub Pages'
author: 'dark-flames'
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: false
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "static"
  deploy-repo:
    description: "The repo expected by GitHub to have the static files needed for your site."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Install typst-ts-cli
      use: taiki-e/cache-cargo-install-action@v2
      with:
        tool: typst-ts-cli
        git: https://github.com/Myriad-Dreamin/typst.ts
        tag: v0.5.0-rc7
        locked: true

    - name: Setup Node.js Environment and Build Frontend
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    
    - name: Build frontend
      shell: bash
      run: |
        yarn install
        yarn build:fe
        yarn build:typ
    - name: Deploy with Zola  
      uses: shalzz/zola-deploy-action@v0.19.1
      env:
        PAGES_BRANCH: ${{ inputs.deploy-branch }}
        GITHUB_TOKEN: ${{ inputs.access-token }}
        REPOSITORY: ${{ inputs.deploy-repo }}