name: 'Build and Deploy to GitHub Pages'
description: 'Build and deploy the static site to GitHub Pages'
author: 'dark-flames'
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: false
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "static"
  deploy-repo:
    description: "The repo expected by GitHub to have the static files needed for your site."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install typst-ts-cli and Build Typst Posts
      run: |
        cargo install --locked --git https://github.com/Myriad-Dreamin/typst.ts typst-ts-cli
    - name: Setup Node.js Environment and Build Frontend
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
    - name: Build frontend
      run: |
        yarn install
        yarn build:typ
        yarn build:frontend
    - name: Deploy with Zola
      uses: shalzz/zola-deploy-action@v0.19.1
      env:
        PAGES_BRANCH: ${{ inputs.deploy-branch }}
        GITHUB_TOKEN: ${{ inputs.access-token }}
        REPOSITORY: ${{ inputs.deploy-repo }}